export const System_prompt = `
The user will first give you a long context and then a query. Your task is to identify a 
sentence or a paragraph in the context that is most related to user's query. 
Find the sentence or paragraph and output the original text. Please return only one sentence.
`;
export const Model_response = "Thanks for providing the context, what's your query?";

export const Test_content = `
Working on his father's farm, Mao read voraciously[8] and developed a "political consciousness" from Zheng Guanying's booklet which lamented the deterioration of Chinese power and argued for the adoption of representative democracy.[9] Mao also read translations of works by Western authors including Adam Smith, Montesquieu, Jean-Jacques Rousseau, Charles Darwin, and Thomas Huxley.[10]: 34  Interested in history, Mao was inspired by the military prowess and nationalistic fervour of George Washington and Napoleon Bonaparte.[11] His political views were shaped by Gelaohui-led protests which erupted following a famine in Changsha, the capital of Hunan; Mao supported the protesters' demands, but the armed forces suppressed the dissenters and executed their leaders.[12] The famine spread to Shaoshan, where starving peasants seized his father's grain. He disapproved of their actions as morally wrong, but claimed sympathy for their situation.[13] At age 16, Mao moved to a higher primary school in nearby Dongshan,[14] where he was bullied for his peasant background.[15]

In 1911, Mao began middle school in Changsha.[16] Revolutionary sentiment was strong in the city, where there was widespread animosity towards Emperor Puyi's absolute monarchy and many were advocating republicanism. The republicans' figurehead was Sun Yat-sen, an American-educated Christian who led the Tongmenghui society.[17] In Changsha, Mao was influenced by Sun's newspaper, The People's Independence (Minli bao),[18] and called for Sun to become president in a school essay.[19] As a symbol of rebellion against the Manchu monarch, Mao and a friend cut off their queue pigtails, a sign of subservience to the emperor.[20]

Inspired by Sun's republicanism, the army rose up across southern China, sparking the Xinhai Revolution. Changsha's governor fled, leaving the city in republican control.[21] Supporting the revolution, Mao joined the rebel army as a private soldier, but was not involved in fighting or combat. The northern provinces remained loyal to the emperor, and hoping to avoid a civil war, Sun—proclaimed "provisional president" by his supporters—compromised with the monarchist general Yuan Shikai. The monarchy was abolished, creating the Republic of China, but the monarchist Yuan became president. With the revolution over, Mao resigned from the army in 1912, after six months as a soldier.[22] Around this time, Mao discovered socialism from a newspaper article; proceeding to read pamphlets by Jiang Kanghu, the student founder of the Chinese Socialist Party, Mao remained interested yet unconvinced by the idea.[23]

Fourth Normal School of Changsha: 1912–1919
Over the next few years, Mao Zedong enrolled and dropped out of a police academy, a soap-production school, a law school, an economics school, and the government-run Changsha Middle School.[24] Studying independently, he spent much time in Changsha's library, reading core works of classical liberalism such as Adam Smith's The Wealth of Nations and Montesquieu's The Spirit of the Laws, as well as the works of western scientists and philosophers such as Darwin, Mill, Rousseau, and Spencer.[25] Viewing himself as an intellectual, years later he admitted that at this time he thought himself better than working people.[26] He was inspired by Friedrich Paulsen, a neo-Kantian philosopher and educator whose emphasis on the achievement of a carefully defined goal as the highest value led Mao to believe that strong individuals were not bound by moral codes but should strive for a great goal.[27] His father saw no use in his son's intellectual pursuits, cut off his allowance and forced him to move into a hostel for the destitute.[28]
`
;